ARG SOURCE_IMAGE
FROM ${SOURCE_IMAGE}

ENV DEBIAN_FRONTEND=noninteractive
ENV ACCEPT_EULA=Y

RUN set -eux; \
    printf '#!/bin/sh\nexit 101\n' > /usr/sbin/policy-rc.d; \
    chmod +x /usr/sbin/policy-rc.d; \
    apt-get update; \
    apt-get -o Dpkg::Options::="--force-confold" \
            -o Dpkg::Options::="--force-confdef" \
            -y upgrade; \
    rm -f /usr/sbin/policy-rc.d; \
    apt-get clean; \
    rm -rf /var/lib/apt/lists/*
